import {API_BASE} from './config.js';
const $=id=>document.getElementById(id);
const labels={risk:'РИСК',attention:'ВНИМАНИЕ',ok:'ОК',unknown:'НЕТ ДАННЫХ'};
let mode='url',busy=false,lastResult=null;
function selectMode(next){if(busy)return;mode=next;for(const x of ['url','text']){$(`mode-${x}`).classList.toggle('selected',x===mode);$(`mode-${x}`).setAttribute('aria-pressed',String(x===mode));$(`${x}-group`).hidden=x!==mode;}$('purchase-url').required=mode==='url';$('purchase-url').disabled=mode!=='url';$('terms-text').required=mode==='text';$('terms-text').disabled=mode!=='text';$('error').hidden=true;}
$('mode-url').onclick=()=>selectMode('url');$('mode-text').onclick=()=>selectMode('text');selectMode('url');
$('terms-text').oninput=()=>{$('text-counter').textContent=`${$('terms-text').value.length.toLocaleString('ru-RU')} / 20 000`;};
function message(text){$('error').textContent=text;$('error').hidden=false;}
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function safeLink(url){try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}}
function showResult(data,demo=false){
  if(!Array.isArray(data.findings)||!Array.isArray(data.sources)||!Array.isArray(data.warnings))throw Error('Не удалось прочитать результат проверки.');
  lastResult={...data,demo};$('result-eyebrow').textContent=demo?'ПРИМЕР · ВЫМЫШЛЕННЫЕ УСЛОВИЯ':'РЕЗУЛЬТАТ ПРОВЕРКИ';
  $('result-level').className=`badge ${Object.hasOwn(labels,data.level)?data.level:'unknown'}`;$('result-level').textContent=labels[data.level]||labels.unknown;
  $('result-summary').textContent=demo?'Демонстрация для условной подписки. Этот результат не относится к введённой ссылке.':`Подтверждённые цитатами пункты: ${data.coverage} из 4. ${data.mode==='text'?'Проверен предоставленный текст.':'Проверено страниц: '+data.sources.length+'.'} Это оценка условий, а не вероятность обмана.`;
  $('findings').replaceChildren();
  for(const f of data.findings){const status=Object.hasOwn(labels,f.status)?f.status:'unknown';const card=node('article',undefined,'finding');card.append(node('span',labels[status],`badge ${status}`),node('h3',f.title),node('p',f.detail));if(f.quote){card.append(node('blockquote',f.quote));const source=data.sources.find(s=>s.id===f.sourceId);const href=safeLink(source?.url);if(href){const a=node('a','Открыть источник ↗');a.href=href;a.target='_blank';a.rel='noopener noreferrer';card.append(a);}else card.append(node('small',demo?'Из условий демонстрационного примера':'Из предоставленного текста'));}$('findings').append(card);}
  $('sources-list').replaceChildren();for(const s of data.sources){const li=node('li');const href=safeLink(s.url);if(href){const a=node('a',s.url);a.href=href;a.target='_blank';a.rel='noopener noreferrer';li.append(a);}else li.textContent=s.title;$('sources-list').append(li);}
  $('warnings-list').replaceChildren(...data.warnings.map(t=>node('li',t)));$('copy-button').textContent='Скопировать результат';$('result').hidden=false;$('result').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});$('result').focus({preventScroll:true});
}
$('analysis-form').onsubmit=async(event)=>{
  event.preventDefault();if(busy)return;
  const local=['localhost','127.0.0.1'].includes(location.hostname),base=API_BASE.replace(/\/$/,'');
  if(!base&&!local){message('Проверка пока не подключена. Посмотрите пример результата ниже.');return;}
  const payload=mode==='url'?{mode,url:$('purchase-url').value.trim()}:{mode,text:$('terms-text').value.trim()};
  if(mode==='url'&&!payload.url.startsWith('https://')){message('Укажите публичную ссылку, начинающуюся с https://.');return;}
  busy=true;$('error').hidden=true;$('result').hidden=true;$('submit-button').disabled=true;$('demo-button').disabled=true;$('mode-url').disabled=true;$('mode-text').disabled=true;$('submit-label').textContent='Проверяем условия';$('status').hidden=false;$('status').textContent=mode==='url'?'Читаем страницу и связанные условия…':'Разбираем предоставленные условия…';
  const update=setTimeout(()=>{$('status').textContent='Сопоставляем выводы с цитатами. Обычно это занимает до минуты…';},10000);
  try{const r=await fetch((base||'/api')+'/analyze',{method:'POST',headers:{'Content-Type':'application/json','X-Prototype-Code':$('access-code').value},body:JSON.stringify(payload),signal:AbortSignal.timeout(120000)});let data;try{data=await r.json();}catch{throw Error('Сервис вернул неожиданный ответ. Повторите попытку позже.');}if(!r.ok){if(data.code==='ACCESS_CODE_REQUIRED'){$('access-group').hidden=false;$('access-code').focus();}throw Error(data.error||'Не удалось завершить проверку.');}showResult(data);
  }catch(e){message(e.name==='TimeoutError'?'Проверка заняла слишком много времени. Попробуйте ещё раз.':e instanceof TypeError?'Не удалось связаться с сервисом. Проверьте соединение и повторите попытку.':e.message);
  }finally{clearTimeout(update);busy=false;$('submit-button').disabled=false;$('demo-button').disabled=false;$('mode-url').disabled=false;$('mode-text').disabled=false;$('submit-label').textContent='Показать риски';$('status').hidden=true;}
};
$('demo-button').onclick=()=>{if(busy)return;$('error').hidden=true;showResult({level:'risk',coverage:3,sources:[{id:'D1',url:null,title:'Вымышленные условия подписки для демонстрации'}],warnings:['Все условия и выводы в этом примере вымышлены.','Даже отсутствие рисков в тексте не гарантирует надёжность продавца.'],findings:[{status:'risk',title:'Пробный период переходит в подписку',detail:'После семи дней спишется 399 ₽. Чтобы избежать списания, отключите продление заранее.',quote:'После пробного периода длительностью 7 дней подписка автоматически продлевается за 399 рублей в месяц.',sourceId:'D1'},{status:'attention',title:'Возврат после начала просмотра ограничен',detail:'В этих условных правилах возврат за текущий период не предусмотрен после начала просмотра.',quote:'После начала просмотра возврат оплаты за текущий период не предусмотрен.',sourceId:'D1'},{status:'ok',title:'Продление можно отключить самостоятельно',detail:'Для отключения следующего списания не нужно обращаться в поддержку.',quote:'Автоматическое продление можно отключить в личном кабинете в любое время.',sourceId:'D1'},{status:'unknown',title:'Региональные ограничения не указаны',detail:'Перед оплатой уточните, доступен ли нужный контент в вашем регионе.',quote:null,sourceId:null}]},true);};
$('copy-button').onclick=async()=>{if(!lastResult)return;const r=lastResult;const text=[r.demo?'ДЕМОНСТРАЦИОННЫЙ ПРИМЕР (вымышленные условия)':'Проверка условий покупки',...r.findings.map(f=>`${labels[f.status]}: ${f.title}\n${f.detail}${f.quote?'\nЦитата: '+f.quote:''}`),'Источники:',...r.sources.map(s=>s.url||s.title),...r.warnings].join('\n\n');try{await navigator.clipboard.writeText(text);$('copy-button').textContent='Скопировано';}catch{$('copy-button').textContent='Выделите и скопируйте текст вручную';}};
